package Logic;

public enum PieceType {
   WHITE_KNIGHT, WHITE_PAWN, WHITE_BISHOP, WHITE_QUEEN, WHITE_KING, WHITE_ROOK,
    BLACK_KNIGHT, BLACK_PAWN, BLACK_BISHOP, BLACK_QUEEN, BLACK_KING, BLACK_ROOK

}

